optimize the script to transform markdown to pdf

diff --git a/bin/md2 b/bin/md2
--- a/bin/md2
+++ b/bin/md2
@@ -13,6 +13,11 @@ adjust_html () {
         s/([^A-Za-z,."'';。 ； ， ： “ ”（ ） 、 ？ 《 》])(<span class="citation"[^>]+>(<a href=[^>]+>)?[A-Za-z])/\1 \2/g' "$1"
 }
 
+adjust_tex () {
+    perl -CSD -Mutf8 -i -pe 's/(``)([\w\p{P}\s]*\p{Han}+[\w\p{P}\s]*)('\'\'')/“\2”/g; \
+    s/(`)([\w\p{P}\s]*\p{Han}+[\w\p{P}\s]*)('\'')/‘\2’/g' "$1"
+}
+
 adjust_docx () {
     local orifile=$(readlink -f "$1")
     echo "$orifile"
@@ -33,16 +38,19 @@ adjust_docx () {
     cd -
 }
 
-openfile=
-bookdown_lua_filter=
+openfile=0
+current_dir=0
+rmd=0
 
-while getopts ':ovr' opt; do
+while getopts ':ovrc' opt; do
     case "$opt" in
         o)  openfile=1
             ;;
         v)  set -v
             ;;
         r)  rmd=1
+            ;;
+        c)  current_dir=1
             ;;
         *)  echo "md2 [-ovr] <output-file> <input-file>"
             exit 1
@@ -56,29 +64,40 @@ outtype="$1"
 infile=$(readlink -f "$2")
 outfile=$(basename "$infile")
 outfile="${outfile%.md}.$outtype"
-[ "$outtype" = "html" ] || {
-    outdir="$HOME/Documents/genfile/$(date +%F)"
-    mkdir -p "$outdir" && cd "$outdir" || exit 
-}
-
-if [ -z $rmd ]; then
-    pandoc +RTS -M512M -RTS "$infile" -d2"$outtype" $bookdown_lua_filter --lua-filter rsbc.lua -o "$outfile" || \
-        { echo "file transform failure"; exit 3; }
+if [ $current_dir -eq 1 ]; then
+    outdir="$(pwd)"
 else
+    outdir="$HOME/Documents/genfile/$(date +%F)"
+    mkdir -p "$outdir" || exit 2
+fi
+
+if [ $rmd -eq 1 ]; then
     Rlib=$(Rscript --vanilla -e 'cat(.libPaths()[1])')
-    pandoc +RTS -M512M -RTS "$infile" -o "$outfile" \
+    pandoc +RTS -M512M -RTS "$infile" -o "$outdir/$outfile" \
         --lua-filter "$Rlib/bookdown/rmarkdown/lua/custom-environment.lua" \
         --lua-filter "$Rlib/rmarkdown/rmarkdown/lua/pagebreak.lua" \
         --lua-filter "$Rlib/rmarkdown/rmarkdown/lua/latex-div.lua" \
         --lua-filter rsbc.lua -d2"$outtype" --variable graphics  || \
         { echo "file transform failure"; exit 3; }
+else
+    pandoc +RTS -M512M -RTS "$infile" -o "$outdir/$outfile" \
+        -d2"$outtype" $bookdown_lua_filter --lua-filter rsbc.lua || \
+        { echo "file transform failure"; exit 3; }
 fi
+
 case "$outtype" in
-    html) adjust_html "$outfile" ;;
-    docx) adjust_docx "$outfile" ;;
+    tex)
+        adjust_tex  "$outdir/$outfile"
+        latexmk -xelatex -quiet -outdir="$outdir" "$outdir/$outfile" 
+        outfile="${outfile%.tex}.pdf"
+        latexmk -c
+        rm "$outdir"/*.{bbl,xml,xdv}
+        ;;
+    html) adjust_html "$outdir/$outfile" ;;
+    docx) adjust_docx "$outdir/$outfile" ;;
 esac
 
-[ -z $openfile ] || nohup xdg-open "$outfile" >/dev/null 2>&1 &
+[ -z $openfile ] || nohup xdg-open "$outdir/$outfile" >/dev/null 2>&1 &
 
 exit 0
 
